version: '2'

services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: r5pgsd
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - r5pgsd-postgres:/var/lib/postgresql/data

  redis:
    image: redis:2.8.22
    ports:
      - '6379:6379'
    volumes:
      - r5pgsd-redis:/var/lib/redis/data

  sidekiq:
    build: .
    links:
      - postgres
      - redis
    command: bundle exec sidekiq --config config/sidekiq.yml.erb
    volumes:
      - .:/r5pgsd
    env_file:
      - .r5pgsd.env

  web:
    build: .
    volumes:
      - .:/r5pgsd
    ports:
      - '3000:3000'
    env_file:
      - .r5pgsd.env

volumes:
  r5pgsd-postgres:
  r5pgsd-redis:
