# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f4a8016406a2c9ad12de92bbf86ef2c674ff4fb64b09b28e70269d1fc2b23c81a2860572701aa07a061e44c22b1c05b4c4127117fac85cb97a339bf7aea55a4

test:
  secret_key_base: 8a468800a9eafe0743167c540868039803ecf01940e2c0af47613aaa205ff03bd18deaa26f780a2f722b701ba6afbecfd1109bd6e81f3a2703bb501ee344040d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
